# =================================================================
# infra/docker-compose.yml
# -----------------------------------------------------------------
# KEEPS THE SYSTEM INTEGRATED: This file is updated to run a
# PostgreSQL database service instead of MongoDB. It also fixes
# the .env file path and removes the obsolete 'version' attribute.
# =================================================================

services:
  db:
    image: postgres:15
    container_name: eduflow_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  web:
    build: .
    container_name: eduflow_web
    command: gunicorn --bind 0.0.0.0:8000 academy_suite.wsgi:application
    volumes:
      - ../:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - db

volumes:
  postgres_data: